import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--epoch', type=int, default=200, help='epoch number')
parser.add_argument('--lr', type=float, default=1e-4, help='learning rate')
parser.add_argument('--batchsize', type=int, default=6, help='training batch size')
parser.add_argument('--trainsize', type=int, default=384, help='training dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=60, help='every n epochs decay learning rate')
parser.add_argument('--load', type=str, default=None, help='train from checkpoints')
parser.add_argument('--gpu_id', type=str, default='0', help='train use gpu')
parser.add_argument('--rgb_root', type=str, default='/home/zqq/桌面/twj/datasource/RGBDCOD/train/image/', help='the training rgb images root')
parser.add_argument('--depth_root', type=str, default='/home/zqq/桌面/twj/datasource/RGBDCOD/train/depth/', help='the training depth images root')
parser.add_argument('--gt_root', type=str, default='/home/zqq/桌面/twj/datasource/RGBDCOD/train/mask/', help='the training gt images root')
parser.add_argument('--test_rgb_root', type=str, default='/home/zqq/桌面/twj/datasource/RGBDCOD/test/CAMO/image/', help='the test rgb images root')
parser.add_argument('--test_depth_root', type=str, default='/home/zqq/桌面/twj/datasource/RGBDCOD/test/CAMO/depth/', help='the test depth images root')
parser.add_argument('--test_gt_root', type=str, default='/home/zqq/桌面/twj/datasource/RGBDCOD/test/CAMO/mask/', help='the test gt images root')
parser.add_argument('--save_path', type=str, default='/home/zqq/桌面/twj/BBS-Net-master/BBSNet_SMT3_cpts/', help='the path to save models and logs')
parser.add_argument('--smt_pretrained', type=str, default='/home/zqq/桌面/twj/BBS-Net-master/smt_base.pth',help='path to SMT pretrained weights')
parser.add_argument('--edge_weight', type=float, default=0.2, help='weight for edge-aware loss')
opt = parser.parse_args()
